export default function Blank() {
  return (<>
    <div className="w-1 h-8 bg-purple-600"></div>
    <div className="w-2 bg-red-600"></div>
    <div className="w-3 bg-yellow-600"></div>
    <div className="w-4 bg-orange-600"></div>
    <div className="w-5 bg-amber-600"></div>
    <div className="w-6 bg-lime-600"></div>
    <div className="bg-teal-600 w-7"></div>
    <div className="w-8 bg-blue-600"></div>
    <div className="bg-pink-600 w-9"></div>
    <div className="w-10 bg-rose-600"></div>
    <div className="w-11 bg-cyan-600"></div>
    <div className="w-12 bg-black"></div>
    <div className="bg-orange-100 w-13"></div>
    <div className="col-span-1 bg-yellow-300 "></div>
    <div className="col-span-2 bg-orange-500"></div>
    <div className="col-span-3 bg-lime-500"></div>
    <div className="col-span-4 bg-teal-300"></div>
    <div className="col-span-5 bg-blue-500"></div>
    <div className="col-span-6 bg-pink-500"></div>
    <div className="col-span-7 bg-violet-600"></div>
    <div className="col-span-8 bg-yellow-400"></div>
    <div className="col-span-9 bg-rose-800"></div>
    <div className="col-span-10 bg-amber-700"></div>
    <div className="col-span-11 bg-emerald-800"></div>
    <div className="col-span-12"></div>
    <div className="col-span-13"></div>
    <div className="col-span-14"></div>
    <div className="col-span-15"></div>
    <div className="col-span-16"></div>
    <div className="col-span-17"></div>
    <div className="col-span-18"></div>
    <div className="col-span-19"></div>
    <div className="col-span-20"></div>
    <div className="col-span-21"></div>
    <div className="col-span-22"></div>
    <div className="col-span-23"></div>
    <div className="col-span-24"></div>
    <div className="col-span-25"></div>
    <div className="col-span-26"></div>
    <div className="col-span-27"></div>
    <div className="col-span-28"></div>
    <div className="col-span-29"></div>
    <div className="col-span-30"></div>
    <div className="col-span-31"></div>
    <div className="col-span-32"></div>
    <div className="col-span-33"></div>
    <div className="col-span-34"></div>
    <div className="col-span-35"></div>
    <div className="col-span-36"></div>
    <div className="col-span-37"></div>
    <div className="col-span-38"></div>
    <div className="col-span-39"></div>
    <div className="col-span-40"></div>
    <div className="col-span-41"></div>
    <div className="col-span-42"></div>
    <div className="col-span-43"></div>
    <div className="col-span-44"></div>
    <div className="col-span-45"></div>
    <div className="col-span-46"></div>
    <div className="col-span-47"></div>
    <div className="col-span-48"></div>
    <div className="col-span-49"></div>
    <div className="col-span-50"></div>
    <div className="col-span-51"></div>
    <div className="col-span-52"></div>
    <div className="col-span-53"></div>
    <div className="col-span-54"></div>
    <div className="col-span-55"></div>
    <div className="col-span-56"></div>
    <div className="col-span-57"></div>
    <div className="col-span-58"></div>
    <div className="col-span-59"></div>
    <div className="col-span-60"></div>
    <div className="col-span-61"></div>
    <div className="col-span-62"></div>
    <div className="col-span-63"></div>
    <div className="col-span-64"></div>
    <div className="col-span-65"></div>
    <div className="col-span-66"></div>
    <div className="col-span-67"></div>
    <div className="col-span-68"></div>
    <div className="col-span-69"></div>
    <div className="col-span-70"></div>
    <div className="col-span-71"></div>
    <div className="col-span-72"></div>
    <div className="col-span-73"></div>
    <div className="col-span-74"></div>
    <div className="col-span-75"></div>
    <div className="col-span-76"></div>
    <div className="col-span-77"></div>
    <div className="col-span-78"></div>
    <div className="col-span-79"></div>
    <div className="col-span-80"></div>
    <div className="col-span-81"></div>
    <div className="col-span-82"></div>
    <div className="col-span-83"></div>
    <div className="col-span-84"></div>
    <div className="col-span-85"></div>
    <div className="col-span-86"></div>
    <div className="col-span-87"></div>
    <div className="col-span-88"></div>
    <div className="col-span-89"></div>
    <div className="col-span-90"></div>
    <div className="col-span-91"></div>
    <div className="col-span-92"></div>
    <div className="col-span-93"></div>
    <div className="col-span-94"></div>
    <div className="col-span-95"></div>
    <div className="col-span-96"></div>
    </>
  )
}