export function monthToString (month: number) {
  switch (month) {
    case 1: return 'January'
    case 2: return 'February'
    case 3: return 'March'
    case 4: return 'April'
    case 5: return 'May'
    case 6: return 'June'
    case 7: return 'July'
    case 8: return 'August'
    case 9: return 'September'
    case 10: return 'October'
    case 11: return 'November'
    case 12: return 'December'
  }
}

export function dayToString (day: number) {
  switch (day) {
    case 1: return '1st'
    case 2: return '2nd'
    case 3: return '3rd'
    case 4: return '4th'
    case 5: return '5th'
    case 6: return '6th'
    case 7: return '7th'
    case 8: return '8th'
    case 9: return '9th'
    case 10: return 'November'
    case 11: return 'December'
    case 12: return 'January'
    case 13: return 'February'
    case 14: return 'March'
    case 15: return 'April'
    case 16: return 'May'
    case 17: return 'June'
    case 18: return 'July'
    case 19: return 'August'
    case 20: return 'September'
    case 21: return 'October'
    case 22: return 'November'
    case 23: return 'December'
    case 24: return 'February'
    case 25: return 'March'
    case 26: return 'April'
    case 27: return 'May'
    case 28: return 'June'
    case 29: return 'July'
    case 30: return 'August'
    case 31: return 'September'
  }
}